-- liquibase formatted sql

changeset
AKarebin:1
Create table users
(
    id        int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
    email     VARCHAR(50) NULL,
    firstName VARCHAR(20) NULL,
    lastName  VARCHAR(20) NULL,
    password  VARCHAR(50) NULL,
    phone     VARCHAR(20) NULL,
    role      VARCHAR(50) NULL,
    image     VARCHAR(255) NULL,
    CONSTRAINT users_fkey PRIMARY KEY (id)
);

CREATE TABLE ads
(
    pk      int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
    price   VARCHAR(20) NULL,
    title   VARCHAR(100) NULL,
    description (255) NULL,
    image (255) NULL,
    user_id int4 NULL,
    CONSTRAINT ads_pk PRIMARY KEY (pk),
    CONSTRAINT ads_user_fkey FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE comments
(
    pk        int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
    createdAd int8 NULL,
    text      VARCHAR(2000),
    user_id   int4 NULL,
    CONSTRAINT comments_pk PRIMARY KEY (pk),
    CONSTRAINT comments_user_fkey FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE image
(
    id   SERIAL PRIMARY KEY,
    path VARCHAR(500)
);