-- liquibase formatted sql

changeset
AKarebin:1

CREATE TABLE images
(
    id   SERIAL PRIMARY KEY,
    path VARCHAR(500),
    CONSTRAINT images_pkey PRIMARY KEY (id)
);


CREATE TABLE users
(
    id        SERIAL PRIMARY KEY,
    email     VARCHAR(50) NULL,
    firstName VARCHAR(20) NULL,
    lastName  VARCHAR(20) NULL,
    password  VARCHAR(50) NULL,
    phone     VARCHAR(20) NULL,
    user_id   INT4 NULL,
    role      VARCHAR(50) NULL,
    image_id  INT4 DEFAULT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT image_user_fkey FOREIGN KEY (image_id) REFERENCES images (id),
    CONSTRAINT image_users_fkey FOREIGN KEY (id) REFERENCES images (id),

);

CREATE TABLE ads
(
    pk       SERIAL PRIMARY KEY,
    price    VARCHAR(20) NULL,
    title    VARCHAR(100) NULL,
    description (255) NULL,
    user_id  int4 NULL,
    image_id int4 NULL,
    CONSTRAINT ads_pk PRIMARY KEY (pk),
    CONSTRAINT ads_user_fkey FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT image_ads_fkey FOREIGN KEY (pk) REFERENCES images (id)
);


CREATE TABLE comments
(
    pk        int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
    createdAd int8 NULL,
    text      VARCHAR(2000),
    user_id   int4 NULL,
    CONSTRAINT comments_pk PRIMARY KEY (pk),
    CONSTRAINT comments_user_fkey FOREIGN KEY (user_id) REFERENCES users (id)
);

